import { registerEnumType } from '@nestjs/graphql';

export enum PermissionGroup {
    USER = "USER",
    INSTITUTION = "INSTITUTION",
    CHURCH = "CHURCH",
    REGION = "REGION",
    CONTACT = "CONTACT",
    ROLE = "ROLE",
    PERMISSION = "PERMISSION",
    DEPARTMENT = "DEPARTMENT",
    COMMUNICATION = "COMMUNICATION",
    DIRECT_MESSAGE = "DIRECT_MESSAGE",
    PROJECT = "PROJECT",
    ACTIVITY = "ACTIVITY",
    ACTIVITY_DOCUMENT = "ACTIVITY_DOCUMENT",
    NOTIFICATION = "NOTIFICATION",
    SETTING = "SETTING",
    SUBSIDY_REQUEST = "SUBSIDY_REQUEST",
    SUBSIDY_STATUS = "SUBSIDY_STATUS",
    SUBSIDY_RECEIPT = "SUBSIDY_RECEIPT",
    EMAIL_SEND = "EMAIL_SEND",
    INVITE = "INVITE",
    ANNUAL_BUDGET = "ANNUAL_BUDGET"
}


registerEnumType(PermissionGroup, { name: 'PermissionGroup', description: undefined })
