import { registerEnumType } from '@nestjs/graphql';

export enum ProjectHistoryType {
    COMMENT = "COMMENT",
    CREATED = "CREATED",
    UPDATED = "UPDATED",
    STATUS_CHANGED = "STATUS_CHANGED",
    BUDGET_UPDATED = "BUDGET_UPDATED",
    DEADLINE_UPDATED = "DEADLINE_UPDATED",
    OWNER_CHANGED = "OWNER_CHANGED",
    CO_OWNER_UPDATED = "CO_OWNER_UPDATED",
    DEPARTMENT_CHANGED = "DEPARTMENT_CHANGED",
    DELETED = "DELETED",
    RESTORED = "RESTORED",
    ADJUSTMENT_NEEDED = "ADJUSTMENT_NEEDED",
    ACTIVITY_CREATED = "ACTIVITY_CREATED",
    ACTIVITY_UPDATED = "ACTIVITY_UPDATED",
    ACTIVITY_DELETED = "ACTIVITY_DELETED",
    SUBSIDY_CREATED = "SUBSIDY_CREATED",
    SUBSIDY_UPDATED = "SUBSIDY_UPDATED",
    SUBSIDY_APPROVED = "SUBSIDY_APPROVED",
    SUBSIDY_REJECTED = "SUBSIDY_REJECTED",
    SUBSIDY_DELETED = "SUBSIDY_DELETED",
    SUBSIDY_DOCUMENT_UPDATED = "SUBSIDY_DOCUMENT_UPDATED",
    SUBSIDY_DOCUMENT_VALIDATED = "SUBSIDY_DOCUMENT_VALIDATED",
    SUBSIDY_DOCUMENT_REJECTED = "SUBSIDY_DOCUMENT_REJECTED"
}


registerEnumType(ProjectHistoryType, { name: 'ProjectHistoryType', description: undefined })
