import { registerEnumType } from '@nestjs/graphql';

export enum ServiceCalendarSource {
    BULK_DEFAULT = "BULK_DEFAULT",
    CHURCH_CONFIRMED = "CHURCH_CONFIRMED"
}


registerEnumType(ServiceCalendarSource, { name: 'ServiceCalendarSource', description: "BULK_DEFAULT = generated by an admin/department-leader bulk pattern (R8.1), shown to the\nchurch leader as a suggestion pending confirmation. CHURCH_CONFIRMED = the leader explicitly\nset or accepted it for their own church — a bulk re-apply must never silently overwrite this." })
